title: 'Public Service Week 2021'
description: Description
url: 'https://www.publicserviceweek.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css

resources_name: news
favicon: /images/PSW_Logo.png
google-analytics: UA-40876833-17
permalink: none
baseurl: ""
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
staging: https://psd-psw-staging.netlify.app
prod: https://psd-psw-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
